// Готовые учебные наборы для русскоязычного ученика: ложные друзья, «неожиданный» род, ser/estar, por/para.

// Ложные друзья: испанское слово похоже на русское, но значит другое.
export const FALSE_FRIENDS = [
  { es: 'la familia', ru: 'семья', note: 'Не «фамилия»! Фамилия — el apellido.', example: 'Mi familia vive en Alicante.', exampleRu: 'Моя семья живёт в Аликанте.' },
  { es: 'el apellido', ru: 'фамилия', note: 'Похоже на «апелляцию», но это фамилия.', example: '¿Cuál es su apellido?', exampleRu: 'Какая у вас фамилия?' },
  { es: 'la carta', ru: 'письмо; меню в ресторане', note: 'Не «карта»! Карта местности — el mapa, банковская — la tarjeta.', example: '¿Nos trae la carta, por favor?', exampleRu: 'Принесёте нам меню, пожалуйста?' },
  { es: 'la tarjeta', ru: 'карточка, банковская карта', note: '«Карта» для оплаты — la tarjeta, а не la carta.', example: '¿Puedo pagar con tarjeta?', exampleRu: 'Можно заплатить картой?' },
  { es: 'el mapa', ru: 'карта (географическая)', note: 'Мужской род, хотя на -a.', example: 'Mira el mapa de la ciudad.', exampleRu: 'Посмотри карту города.' },
  { es: 'la tienda', ru: 'магазин', note: 'Русское «магазин» по-испански — la tienda; el almacén — склад.', example: 'La tienda abre a las diez.', exampleRu: 'Магазин открывается в десять.' },
  { es: 'el almacén', ru: 'склад', note: 'Похоже на «магазин», но это склад (grandes almacenes — универмаг).', example: 'La mercancía está en el almacén.', exampleRu: 'Товар на складе.' },
  { es: 'la revista', ru: 'журнал', note: 'Не «ревизия». А el diario — газета или дневник.', example: 'Compro una revista en el quiosco.', exampleRu: 'Покупаю журнал в киоске.' },
  { es: 'la reclamación', ru: 'жалоба, претензия', note: 'Не «реклама»! Реклама — la publicidad, объявление — el anuncio.', example: 'Quiero poner una reclamación.', exampleRu: 'Я хочу подать жалобу.' },
  { es: 'el anuncio', ru: 'объявление; рекламный ролик', note: 'Реклама по ТВ и объявления — anuncios.', example: 'He visto un anuncio de un piso.', exampleRu: 'Я видел объявление о квартире.' },
  { es: 'el instituto', ru: 'средняя школа (с 12 до 18 лет)', note: 'Не вуз! Вуз — la universidad.', example: 'Mi hijo va al instituto.', exampleRu: 'Мой сын ходит в среднюю школу.' },
  { es: 'el colegio', ru: 'школа (обычно начальная)', note: 'Не «колледж» и не «коллегия».', example: 'El colegio está al lado de casa.', exampleRu: 'Школа рядом с домом.' },
  { es: 'la academia', ru: 'частные курсы, учебный центр', note: 'Academia de inglés — курсы английского, а не академия наук.', example: 'Estudio español en una academia.', exampleRu: 'Я учу испанский на курсах.' },
  { es: 'el despacho', ru: 'кабинет, офис', note: 'Русский «кабинет» — el despacho, а la cabina — кабинка, будка.', example: 'El director está en su despacho.', exampleRu: 'Директор у себя в кабинете.' },
  { es: 'la cabina', ru: 'кабинка, будка', note: 'Не «кабинет».', example: 'La cabina de teléfono ya no funciona.', exampleRu: 'Телефонная будка уже не работает.' },
  { es: 'el bufete', ru: 'адвокатская контора', note: 'Не «буфет»! Буфет (мебель) — el aparador.', example: 'Trabaja en un bufete de abogados.', exampleRu: 'Работает в адвокатской конторе.' },
  { es: 'el balón', ru: 'мяч', note: 'Не «баллон». Газовый баллон — la bombona.', example: 'Los niños juegan con el balón.', exampleRu: 'Дети играют с мячом.' },
  { es: 'la bombona', ru: 'газовый баллон', note: 'Не «бомба».', example: 'Hay que cambiar la bombona de butano.', exampleRu: 'Нужно поменять баллон с бутаном.' },
  { es: 'la batería', ru: 'аккумулятор; ударная установка', note: 'Батарея отопления — el radiador.', example: 'El móvil se ha quedado sin batería.', exampleRu: 'У телефона села батарея.' },
  { es: 'la pila', ru: 'батарейка', note: 'Не «пила»! Пила — la sierra.', example: 'El mando necesita pilas nuevas.', exampleRu: 'Пульту нужны новые батарейки.' },
  { es: 'la tableta', ru: 'плитка шоколада; планшет', note: 'Не «таблетка»! Таблетка — la pastilla.', example: 'Una tableta de chocolate, por favor.', exampleRu: 'Плитку шоколада, пожалуйста.' },
  { es: 'la pastilla', ru: 'таблетка', note: 'Таблетка — pastilla, а не tableta.', example: 'Tómate una pastilla para el dolor.', exampleRu: 'Выпей таблетку от боли.' },
  { es: 'el prospecto', ru: 'инструкция к лекарству; листовка', note: 'Не «проспект»! Проспект (улица) — la avenida.', example: 'Lee el prospecto antes de tomarlo.', exampleRu: 'Прочитай инструкцию перед приёмом.' },
  { es: 'la avenida', ru: 'проспект, широкая улица', note: 'Русский «проспект» — avenida.', example: 'Vivo en la avenida del Mediterráneo.', exampleRu: 'Я живу на проспекте Средиземноморья.' },
  { es: 'constipado', ru: 'простуженный', note: 'Не «констипация» (запор — estreñimiento).', example: 'Estoy constipado, me duele la garganta.', exampleRu: 'Я простыл, болит горло.' },
  { es: 'la marca', ru: 'марка (бренд); отметка', note: 'Почтовая марка — el sello.', example: '¿De qué marca es tu coche?', exampleRu: 'Какой марки твоя машина?' },
  { es: 'el sello', ru: 'почтовая марка; печать', note: 'Марка на письмо — sello, а не marca.', example: 'Necesito un sello para esta carta.', exampleRu: 'Мне нужна марка для этого письма.' },
  { es: 'la lista', ru: 'список', note: 'Не «лист»! Лист бумаги — la hoja.', example: 'Haz la lista de la compra.', exampleRu: 'Составь список покупок.' },
  { es: 'la hoja', ru: 'лист (бумаги, дерева)', note: 'Лист — hoja, а lista — список.', example: 'Dame una hoja de papel.', exampleRu: 'Дай мне лист бумаги.' },
  { es: 'el argumento', ru: 'сюжет; довод', note: 'В кино и книгах argumento — сюжет.', example: 'El argumento de la película es muy original.', exampleRu: 'Сюжет фильма очень оригинальный.' },
  { es: 'la agenda', ru: 'ежедневник, расписание', note: 'Не «повестка дня» в первую очередь.', example: 'Lo apunto en la agenda.', exampleRu: 'Запишу в ежедневник.' },
  { es: 'el director', ru: 'директор; режиссёр', note: 'Director de cine — кинорежиссёр.', example: 'Almodóvar es un director famoso.', exampleRu: 'Альмодовар — известный режиссёр.' },
  { es: 'la carrera', ru: 'учёба в университете; забег', note: 'Hacer la carrera — учиться в вузе, а не «делать карьеру».', example: 'Estudió la carrera de Derecho.', exampleRu: 'Он учился на юридическом.' },
  { es: 'la cola', ru: 'очередь; хвост', note: 'Hacer cola — стоять в очереди.', example: 'Hay mucha cola en el supermercado.', exampleRu: 'В супермаркете большая очередь.' },
  { es: 'el banco', ru: 'банк; скамейка', note: 'Не «банка»! Банка — el bote или el tarro.', example: 'Nos sentamos en un banco del parque.', exampleRu: 'Мы сели на скамейку в парке.' },
  { es: 'el bote', ru: 'банка; лодка', note: 'Банка (консервная, стеклянная) — bote или tarro.', example: 'Un bote de tomate triturado.', exampleRu: 'Банка томатной пасты.' },
  { es: 'el globo', ru: 'воздушный шар', note: 'Глобус — el globo terráqueo.', example: 'Compramos globos para el cumpleaños.', exampleRu: 'Мы купили шарики на день рождения.' },
  { es: 'la gorra', ru: 'кепка', note: 'Не «гора»! Гора — la montaña.', example: 'Ponte la gorra, hace mucho sol.', exampleRu: 'Надень кепку, очень солнечно.' },
  { es: 'la ducha', ru: 'душ', note: 'Не «душа»! Душа — el alma.', example: 'Me doy una ducha y salgo.', exampleRu: 'Приму душ и выйду.' },
  { es: 'la boda', ru: 'свадьба', note: 'Не «вода»! Вода — el agua.', example: 'La boda es en junio.', exampleRu: 'Свадьба в июне.' },
  { es: 'el dedo', ru: 'палец', note: 'Не «дед»! Дедушка — el abuelo.', example: 'Me he cortado el dedo.', exampleRu: 'Я порезал палец.' },
  { es: 'la cara', ru: 'лицо', note: 'Не «кара». А caro — дорогой.', example: 'Tienes buena cara hoy.', exampleRu: 'Ты сегодня хорошо выглядишь.' },
  { es: 'el tío', ru: 'дядя; парень, чувак (разг.)', note: 'Не «тётя»! Тётя — la tía (и «девушка» в разговоре).', example: '¡Qué tío más majo!', exampleRu: 'Какой славный парень!' },
  { es: 'la cortina', ru: 'штора, занавеска', note: 'Не «картина»! Картина — el cuadro.', example: 'Cierra las cortinas, por favor.', exampleRu: 'Задёрни шторы, пожалуйста.' },
  { es: 'el cuadro', ru: 'картина', note: 'Не «квадрат» (квадрат — el cuadrado).', example: 'Hay un cuadro de Sorolla en el salón.', exampleRu: 'В гостиной висит картина Сорольи.' },
  { es: 'la factura', ru: 'счёт (за услуги)', note: 'Не «фактура» ткани. Счёт в баре — la cuenta.', example: 'Ha llegado la factura de la luz.', exampleRu: 'Пришёл счёт за свет.' },
  { es: 'la urbanización', ru: 'жилой комплекс, посёлок', note: 'Не процесс «урбанизации», а конкретный жилой комплекс.', example: 'Vivimos en una urbanización con piscina.', exampleRu: 'Мы живём в жилом комплексе с бассейном.' },
  { es: 'la planta', ru: 'этаж; растение', note: 'В магазине и доме planta — этаж: planta baja — первый этаж.', example: 'Los probadores están en la segunda planta.', exampleRu: 'Примерочные на втором этаже (по-русски — на третьем).' },
  { es: 'la caravana', ru: 'пробка (на дороге); дом на колёсах', note: 'Не только «караван».', example: 'Hay caravana en la autopista.', exampleRu: 'На автостраде пробка.' },
  { es: 'el plato', ru: 'тарелка; блюдо', note: 'Не «плато». Primer plato — первое блюдо.', example: 'De primer plato, ensalada.', exampleRu: 'На первое — салат.' },
];

// Существительные, где род не угадать по окончанию или он не совпадает с русским.
export const GENDER_SET = [
  { es: 'la mano', ru: 'рука (кисть)', gender: 'la', note: 'Женский род, хотя на -o.' },
  { es: 'el día', ru: 'день', gender: 'el', note: 'Мужской род, хотя на -a.' },
  { es: 'el problema', ru: 'проблема', gender: 'el', note: 'Слова на -ma греческого происхождения — мужского рода.' },
  { es: 'el tema', ru: 'тема', gender: 'el', note: 'Мужской род (-ma).' },
  { es: 'el idioma', ru: 'язык (иностранный)', gender: 'el', note: 'Мужской род (-ma).' },
  { es: 'el sistema', ru: 'система', gender: 'el', note: 'Мужской род (-ma).' },
  { es: 'el programa', ru: 'программа', gender: 'el', note: 'Мужской род (-ma).' },
  { es: 'el clima', ru: 'климат', gender: 'el', note: 'Мужской род (-ma).' },
  { es: 'el planeta', ru: 'планета', gender: 'el', note: 'Мужской род, хотя на -a.' },
  { es: 'el sofá', ru: 'диван', gender: 'el', note: 'Мужской род, хотя на -á.' },
  { es: 'la foto', ru: 'фотография', gender: 'la', note: 'Сокращение от la fotografía — женский род.' },
  { es: 'la moto', ru: 'мотоцикл', gender: 'la', note: 'Сокращение от la motocicleta.' },
  { es: 'la radio', ru: 'радио', gender: 'la', note: 'Женский род (в Испании).' },
  { es: 'el agua', ru: 'вода', gender: 'el', note: 'Женский род, но артикль el перед ударным a-: el agua fría.' },
  { es: 'el mar', ru: 'море', gender: 'el', note: 'Обычно мужской род (поэты и моряки говорят la mar).' },
  { es: 'la leche', ru: 'молоко', gender: 'la', note: 'Женский род — в русском средний.' },
  { es: 'la miel', ru: 'мёд', gender: 'la', note: 'Женский род — в русском мужской.' },
  { es: 'la clase', ru: 'класс; урок', gender: 'la', note: 'Женский род — в русском «класс» мужского.' },
  { es: 'el dolor', ru: 'боль', gender: 'el', note: 'Мужской род — в русском женский.' },
  { es: 'la nariz', ru: 'нос', gender: 'la', note: 'Женский род — в русском мужской.' },
  { es: 'el árbol', ru: 'дерево', gender: 'el', note: 'Мужской род — в русском средний.' },
  { es: 'la flor', ru: 'цветок', gender: 'la', note: 'Женский род — в русском мужской.' },
  { es: 'la gente', ru: 'люди', gender: 'la', note: 'Единственное число женского рода: la gente es simpática.' },
  { es: 'la calle', ru: 'улица', gender: 'la', note: 'Женский род, на -e род не угадать.' },
  { es: 'el coche', ru: 'машина', gender: 'el', note: 'Мужской род — в русском «машина» женского.' },
  { es: 'la noche', ru: 'ночь', gender: 'la', note: 'Женский род, на -e.' },
  { es: 'el viaje', ru: 'поездка, путешествие', gender: 'el', note: 'Мужской род (-aje).' },
  { es: 'la parte', ru: 'часть', gender: 'la', note: 'Женский род, на -e.' },
  { es: 'el puente', ru: 'мост', gender: 'el', note: 'Мужской род, на -e.' },
  { es: 'la ciudad', ru: 'город', gender: 'la', note: 'Слова на -dad — женского рода. В русском «город» мужского.' },
];

// Контрастные мини-упражнения. s — предложение с пропуском «___».
export const SER_ESTAR = [
  { s: 'Mi hermano ___ médico.', a: 'es', o: ['es', 'está'], why: 'Профессия → ser.' },
  { s: 'Mi hermano ___ en el hospital.', a: 'está', o: ['es', 'está'], why: 'Где находится человек → estar.' },
  { s: 'La película ___ aburrida.', a: 'es', o: ['es', 'está'], why: 'Свойство: фильм скучный → ser.' },
  { s: 'Hoy no hago nada, ___ aburrido.', a: 'estoy', o: ['soy', 'estoy'], why: 'Мне скучно — состояние → estar. «Soy aburrido» — «я зануда».' },
  { s: 'Juan ___ muy listo, saca buenas notas.', a: 'es', o: ['es', 'está'], why: 'Ser listo — умный (черта характера).' },
  { s: '¿___ listo? Nos vamos ya.', a: 'Estás', o: ['Eres', 'Estás'], why: 'Estar listo — готов (состояние).' },
  { s: 'La fiesta ___ en casa de Ana.', a: 'es', o: ['es', 'está'], why: 'Где проходит событие → ser (а не estar).' },
  { s: 'Benidorm ___ en la provincia de Alicante.', a: 'está', o: ['es', 'está'], why: 'Где находится место → estar.' },
  { s: 'Esta paella ___ riquísima.', a: 'está', o: ['es', 'está'], why: 'Вкус конкретного блюда сейчас → estar.' },
  { s: 'La paella ___ un plato típico valenciano.', a: 'es', o: ['es', 'está'], why: 'Определение, что это такое → ser.' },
  { s: 'Mi abuela ___ muy mayor.', a: 'es', o: ['es', 'está'], why: 'Возраст как характеристика → ser.' },
  { s: '¡Qué guapa ___ hoy con ese vestido!', a: 'estás', o: ['eres', 'estás'], why: 'Сегодня выглядишь → estar (временно).' },
  { s: 'Mis vecinos ___ ingleses.', a: 'son', o: ['son', 'están'], why: 'Происхождение, национальность → ser.' },
  { s: 'La tienda ___ cerrada los domingos.', a: 'está', o: ['es', 'está'], why: 'Результат действия (закрыто) → estar.' },
  { s: '___ las ocho y media.', a: 'Son', o: ['Son', 'Están'], why: 'Время → ser.' },
  { s: 'El café ___ frío, pide otro.', a: 'está', o: ['es', 'está'], why: 'Состояние сейчас → estar.' },
  { s: 'Mi novia ___ de Valencia.', a: 'es', o: ['es', 'está'], why: 'Откуда родом → ser de.' },
  { s: 'Nosotros ___ de vacaciones en Altea.', a: 'estamos', o: ['somos', 'estamos'], why: 'Estar de vacaciones — временное положение.' },
  { s: 'Este piso ___ muy caro.', a: 'es', o: ['es', 'está'], why: 'Цена как свойство → ser. (Estar caro — «подорожал сейчас».)' },
  { s: 'Hoy ___ muy cansado, he trabajado mucho.', a: 'estoy', o: ['soy', 'estoy'], why: 'Усталость — состояние → estar.' },
  { s: 'La puerta ___ de madera.', a: 'es', o: ['es', 'está'], why: 'Материал → ser de.' },
  { s: 'La ventana ___ abierta.', a: 'está', o: ['es', 'está'], why: 'Положение, результат → estar.' },
  { s: '___ prohibido fumar aquí.', a: 'Está', o: ['Es', 'Está'], why: 'Устойчивое выражение: está prohibido.' },
  { s: 'El concierto ___ a las diez.', a: 'es', o: ['es', 'está'], why: 'Когда происходит событие → ser.' },
];

export const POR_PARA = [
  { s: 'Este regalo es ___ ti.', a: 'para', o: ['por', 'para'], why: 'Получатель → para.' },
  { s: 'Gracias ___ tu ayuda.', a: 'por', o: ['por', 'para'], why: 'Причина благодарности → por.' },
  { s: 'Salgo ___ Madrid mañana.', a: 'para', o: ['por', 'para'], why: 'Направление, пункт назначения → para.' },
  { s: 'Damos un paseo ___ la playa.', a: 'por', o: ['por', 'para'], why: 'Движение по месту, через → por.' },
  { s: 'Estudio español ___ hablar con mis vecinos.', a: 'para', o: ['por', 'para'], why: 'Цель (чтобы) → para + инфинитив.' },
  { s: 'Lo hago ___ ti, porque te quiero.', a: 'por', o: ['por', 'para'], why: 'Ради кого-то, из-за → por.' },
  { s: 'Te llamo ___ teléfono.', a: 'por', o: ['por', 'para'], why: 'Способ, средство связи → por.' },
  { s: 'El informe es ___ el lunes.', a: 'para', o: ['por', 'para'], why: 'Срок → para.' },
  { s: 'Vivo en Benidorm ___ el clima.', a: 'por', o: ['por', 'para'], why: 'Причина → por.' },
  { s: 'Compré el sofá ___ 300 euros.', a: 'por', o: ['por', 'para'], why: 'Цена, обмен → por.' },
  { s: '___ la mañana voy al gimnasio.', a: 'Por', o: ['Por', 'Para'], why: 'Часть дня → por la mañana.' },
  { s: '___ mí, el mejor arroz es el de Valencia.', a: 'Para', o: ['Por', 'Para'], why: 'Мнение (по-моему) → para mí.' },
  { s: 'Trabajo ___ una empresa inglesa.', a: 'para', o: ['por', 'para'], why: 'На кого работаешь (работодатель) → para.' },
  { s: 'Pasa ___ casa cuando quieras.', a: 'por', o: ['por', 'para'], why: 'Pasar por — заглянуть куда-то → por.' },
  { s: 'Esta crema es ___ el sol.', a: 'para', o: ['por', 'para'], why: 'Назначение (для чего) → para.' },
  { s: 'Te cambio mi bici ___ tu patinete.', a: 'por', o: ['por', 'para'], why: 'Обмен (одно на другое) → por.' },
  { s: 'La casa fue construida ___ mi abuelo.', a: 'por', o: ['por', 'para'], why: 'Кем сделано (пассив) → por.' },
  { s: 'Hay un autobús ___ el aeropuerto cada hora.', a: 'para', o: ['por', 'para'], why: 'Куда идёт автобус → para.' },
  { s: '___ fin es viernes.', a: 'Por', o: ['Por', 'Para'], why: 'Устойчивое выражение: por fin — наконец.' },
  { s: '¿___ qué estudias español? — Porque vivo aquí.', a: 'Por', o: ['Por', 'Para'], why: '¿Por qué? — почему (причина).' },
  { s: '¿___ qué sirve este botón?', a: 'Para', o: ['Por', 'Para'], why: '¿Para qué? — для чего (цель).' },
];
